name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.7.2"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: â˜‘ï¸ Swift Select
        uses: swift-actions/setup-swift@v1
        with:
            swift-version: ${{ matrix.swift }}

      - name: â¬‡ï¸ Get Sources
        uses: actions/checkout@v3.3.0

      - name: ğŸ› ï¸ Build Package
        run: swift build -v

      - name: ğŸ” Test Package
        run: swift build -v
        if: matrix.os == 'ubuntu-latest'

      - name: ğŸ€ Code Coverage (Code Climate)
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: |
            swift test --enable-code-coverage
          debug: true
          coverageLocations: ${{github.workspace}}/.build/debug/codecov/*.json:lcov-json
        if: matrix.os == 'macos-latest'
